version: '3'
services:
  app:
    build: docker/php
    container_name: skillup_app
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.17
    container_name: skillup_nginx
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/skillup.local.conf:/etc/nginx/conf.d/skillup.local.conf
    depends_on:
      - app
  db:
    image: mysql:8.0.22
    ports:
      - 13306:3306
    container_name: andy_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: andy_db
      MYSQL_USER: andy_user
      MYSQL_PASSWORD: andy_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'lamp-phpmyadmin'
    depends_on:
      - db
    ports:
      - '8003:80'
    volumes:
      - /sessions
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini